name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Set up JDK 17
      run: |
        wget https://download.java.net/java/17/latest/jdk-17_linux-x64_bin.tar.gz
        tar xzf jdk-17_linux-x64_bin.tar.gz
        sudo mv jdk-17 $JAVA_HOME

    - name: Build with Gradle
      run: ./gradlew build --info

    - name: Run tests
      run: ./gradlew test
